### ISSUE TITLE
Pencil tool does not work since I updated Fiji

### ISSUE THREAD

**Issue by delgehyr** [imagej/imagej-plugins-tools#18] opened 2016-05-23 09:42 UTC
I need to draw dots on a composite image in one of the channel. It used to work nicely but since I updated Fiji this morning the pencil tool behave like an eraser.
Could you help me on that.
Best

**Comment by imagejan** [comment] 2016-05-23 10:17
I cannot reproduce with an up-to-date Fiji installation. Are you sure you've correctly set the current foreground color for drawing? On composite images, you draw on the currently active channel with the current (grayscale) value of your foreground color. To get a more intuitive drawing behavior, you can switch the display mode to grayscale instead of composite using the Channels Tool.

Also, please note the this github repository contains the ImageJ2 UI tools. In a standard Fiji installation, you see the [ImageJ 1.x](https://github.com/imagej/imagej1) user interface. The pencil tool works fine for me in both modern and legacy UI, so I'm closing this issue. If you continue to have problems please report the issue on the [ImageJ user forum](http://forum.imagej.net/).

**Closed as completed by imagejan** 2016-05-23 10:17 UTC
